backend:
  name: git-gateway
  branch: main
  repo: VA-Software-Solutions/website-netlify
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "services"
    label: "Services"
    folder: "src/pages/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "service-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "jobs"
    label: "Jobs"
    folder: "src/pages/careers"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "job-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Skills", name: "skills", widget: "list" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: About,
              name: about,
              widget: object,
              fields:
                [
                  { label: "Primary title", name: primaryTitle, widget: string },
                  { label: "Secondary title", name: secondaryTitle, widget: string },
                  { label: "Subheading", name: subheading, widget: text },
                  { label: "Content", name: content, widget: markdown },
                ],
            }
          - {
              label: Carrers,
              name: carrers,
              widget: object,
              fields:
                [
                  { label: "Primary title", name: primaryTitle, widget: string },
                  { label: "Secondary title", name: secondaryTitle, widget: string },
                  { label: "Subheading", name: subheading, widget: text }
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Description, name: description, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: About,
              name: about,
              widget: object,
              fields:
                [
                  { label: "Primary title", name: primaryTitle, widget: string },
                  { label: "Secondary title", name: secondaryTitle, widget: string },
                  { label: "Subheading", name: subheading, widget: text },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  { label: "Content", name: content, widget: markdown }
                ]
            }
          - {
              label: Core values,
              name: values,
              widget: object,
              fields:
                [
                  { label: "Primary title", name: primaryTitle, widget: string },
                  { label: "Secondary title", name: secondaryTitle, widget: string },
                  {
                    label: Cards,
                    name: cards,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Description, name: description, widget: string, required: false },
                        { label: Icon, name: icon, widget: select, options: 
                          ["support", "rocket2", "code-clean", "group", "badge1", "love","graph-bar", "tick"] 
                        
                        },
                      ],
                  } 
                ],
            }
          - {
              label: Team,
              name: team,
              widget: object,
              fields:
                [
                  { label: "Primary title", name: primaryTitle, widget: string },
                  { label: "Secondary title", name: secondaryTitle, widget: string },
                  { label: "Subheading", name: subheading, widget: string },
                  {
                    label: Team members,
                    name: cards,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: Position, name: position, widget: string, required: false },
                        {
                          label: Image,
                          name: image,
                          widget: object,
                          fields:
                            [
                              { label: Image, name: image, widget: image },
                              { label: Alt, name: alt, widget: string },
                            ],
                        },
                      ],
                  } 
                ],
            }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
